In [1]:
import numpy as np

m1 = np.zeros((3, 4), dtype=int)
m1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [2]:
import numpy as np

m2 = np.zeros((3, 4), dtype=int)
m2[0, :] = 1
m2

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [3]:
import numpy as np

m3 = np.zeros((3, 4), dtype=int)
m3[-1, :] = np.arange(5, 9)
m3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [5, 6, 7, 8]])

In [4]:
import numpy as np

v4 = np.zeros(10, dtype=int)
v4[::2] = 2    # índices pares: 0, 2, 4, 6, 8
v4[1::2] = 1   # índices impares: 1, 3, 5, 7, 9
v4

array([2, 1, 2, 1, 2, 1, 2, 1, 2, 1])

In [5]:
import numpy as np

tablero = np.zeros((8, 8), dtype=int)
tablero[1::2, ::2] = 1   # filas impares, columnas pares
tablero[::2, 1::2] = 1   # filas pares, columnas impares
tablero

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [6]:
import numpy as np

rng = np.random.default_rng(42)
m6 = np.round(rng.random((5, 5)), 4)
print("Matriz:\n", m6)
print("Mínimo:", np.min(m6))
print("Máximo:", np.max(m6))

Matriz:
 [[0.774  0.4389 0.8586 0.6974 0.0942]
 [0.9756 0.7611 0.7861 0.1281 0.4504]
 [0.3708 0.9268 0.6439 0.8228 0.4434]
 [0.2272 0.5546 0.0638 0.8276 0.6317]
 [0.7581 0.3545 0.9707 0.8931 0.7784]]
Mínimo: 0.0638
Máximo: 0.9756


In [7]:
import numpy as np

m7 = (m6 - np.min(m6)) / (np.max(m6) - np.min(m6))
print("Matriz normalizada:\n", np.round(m7, 4))
print("Nuevo mínimo:", np.min(m7))
print("Nuevo máximo:", np.max(m7))

Matriz normalizada:
 [[0.7789 0.4114 0.8717 0.6949 0.0333]
 [1.     0.7648 0.7922 0.0705 0.424 ]
 [0.3367 0.9465 0.6362 0.8324 0.4163]
 [0.1792 0.5383 0.     0.8377 0.6228]
 [0.7615 0.3188 0.9946 0.9095 0.7837]]
Nuevo mínimo: 0.0
Nuevo máximo: 1.0
